### ISSUE TITLE
iOS添加了高德的key，但是运行起来还是一直提示appkey为空

### ISSUE THREAD

**Issue by JankinHou** [shunFSKi/flutter_amap_plugin#7]

**Comment by JankinHou** [comment]
[AMapFoundationKit][Info] : 错误信息：apiKey为空，请正确设置AMapServices.apiKey。请在 AppDelegate.m 文件的 didFinishLaunchingWithOptions 方法中配置高德 Key。

**Comment by shunFSKi** [comment]
你好，这个项目本质上还是属于学习类的插件，主要是提供给初学者一些基本的插件编写思路，所以已经很久没有更新了。
如果项目当中需要地图导航类的功能，还是建议根据项目本身去修改此插件或者可以选择其他更加稳定持续维护的插件来放入项目当中，谢谢。
